# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: author

# No asigna reviewers si la PR es draft
skipDraft: true        

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - Pax16gamedev
  - iscarina
  - mamartdu

# How many reviewers to add. Default is 1 if omitted. 0 means all reviewers.
numberOfReviewers: 0

# A list of keywords to be skipped the process that add reviewers if pull requests include it
# skipKeywords:
#   - wip
#   - draft
